on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  if_merged:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GH_TOKEN: ${{ github.token }}
      run: |
        pwd
        ls -ltr
        git log -n 2
        echo "gh pr reopen $PR_NUMBER"
        git log -n 2
        gh pr checkout $PR_NUMBER
        git log -n 2
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"
        echo The PR was merged
        echo $PR_NUMBER
        touch $PR_NUMBER
        git add $PR_NUMBER
        git commit -am "test commit"
        echo "gh pr merge $PR_NUMBER"
        git push
        echo git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
