on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GH_TOKEN: ${{ github.token }}
      run: |
        versionpath=qick_lib/qick/VERSION
        gh pr checkout $PR_NUMBER
        file_version=$(cut -d '.' -f 3 "$versionpath")
        echo "PR: $PR_NUMBER file: $file_version"
        if [ $file_version != $PR_NUMBER ]; then
          echo "updating VERSION"
          echo "$(cut -d '.' -f -2 $versionpath).$PR_NUMBER" > "$versionpath"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git add "$versionpath"
          git commit -am "update version"
          git push
        fi
